spring.application.name=gps

# === Database Configuration ===
spring.datasource.url=jdbc:postgresql://localhost:5432/gps
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatically create or update tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console (for debugging)
spring.jpa.show-sql=true

# Optional: Format the SQL output
spring.jpa.properties.hibernate.format_sql=true

# Server Port (default 8080)
# server.port=8080

# Timezone (optional, to ensure timestamp consistency)
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Jakarta

spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha

